### ISSUE TITLE
sample dataset for Constructing benchmark test sets for biological sequence analysis using independent set algorithms

### ISSUE THREAD

**Issue by Alice-yyt** [spetti/split_for_benchmarks#1]
Hello author, could you please give me some sample dataset to learn the method in the paper: _Constructing benchmark test sets for biological sequence analysis using independent set algorithms? Thank you very much!

**Comment by spetti** [comment]
You can use any MSA or multi-MSA, e.g. a current release of Pfam http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/
